# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d1ca63c587c8db6819d436ea52277ab8ad87c81afaa80d955c5c54764b4e1fb0d403cc836c0818cea11945974fdeeb39313a62de256d6f50753ceb81cb1640e

test:
  secret_key_base: c1231cf2c621d5d90202e114ae2c153efb68015607a2ce512fdf6a47b775758c1e45ec28454e3730496634a41f54081d898c5ed73c36e9f5a6a47d40629b012e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
